### ISSUE TITLE
Which part of the code/blog refers to learn?  [NOT A BUG rather a QUESTION/DISCUSSION]

### ISSUE THREAD

**Issue by VigneshHexo** [huggingface/search-and-learn#24]
Thanks for the excellent work. I enjoyed reading the [blog](https://huggingface.co/spaces/HuggingFaceH4/blogpost-scaling-test-time-compute) as well the repo. I understand there is detailed information on the search methodologies but I am curious to know is there something about learn in this repo/blog?

**Comment by lewtun** [comment]
Yes, we plan to include code to train PRMs and other methods in this repo in the near future. Stay tuned!

**Comment by VigneshHexo** [comment]
Hi @lewtun 
Any updates on this yet?

**Comment by VigneshHexo** [comment]
Hi @lewtun
Any updates on this yet?
